'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Download, Lock, Loader2 } from 'lucide-react';
import { TierBadge } from '@/components/ui/TierBadge';
import { toast } from 'sonner';

interface ExportPdfButtonProps {
  tier: string;
  contentId: string;
  label?: string;
}

export function ExportPdfButton({ tier, contentId, label = 'Export PDF' }: ExportPdfButtonProps) {
  const [loading, setLoading] = useState(false);
  const isMax = tier === 'max';

  async function handleExport() {
    if (!isMax) return;
    setLoading(true);

    // Use browser print to PDF
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      toast.error('Please allow popups to export');
      setLoading(false);
      return;
    }

    try {
      const res = await fetch(`/api/export/${contentId}`);
      const data = await res.json();

      if (!res.ok) {
        printWindow.close();
        toast.error(data.error || 'Export failed');
        return;
      }

      let html = `<!DOCTYPE html><html><head><title>MedStudy Export</title>
        <style>
          body { font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #1a1a2e; }
          h1 { font-size: 24px; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }
          h2 { font-size: 16px; color: #6366f1; margin-top: 24px; }
          .item { border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin: 12px 0; page-break-inside: avoid; }
          .correct { color: #059669; font-weight: 600; }
          .wrong { color: #dc2626; }
          .explanation { background: #f0f9ff; padding: 8px 12px; border-radius: 6px; font-size: 13px; margin-top: 8px; }
          .meta { font-size: 12px; color: #64748b; }
          .option { padding: 4px 0; font-size: 14px; }
          .option.is-correct { color: #059669; font-weight: 600; }
          .option.is-wrong { color: #dc2626; text-decoration: line-through; }
          @media print { body { padding: 0; } }
        </style>
      </head><body>`;

      if (contentId === 'wrong-answers' && data.wrongAnswers) {
        html += `<h1>Wrong Answers Review</h1><p class="meta">${data.wrongAnswers.length} questions · Exported ${new Date().toLocaleDateString()}</p>`;
        let currentSubject = '';
        for (const q of data.wrongAnswers) {
          if (q.subject && q.subject !== currentSubject) {
            currentSubject = q.subject;
            html += `<h2>${currentSubject}</h2>`;
          }
          html += `<div class="item">`;
          html += `<p><strong>${q.question}</strong></p>`;
          if (q.topic) html += `<p class="meta">${q.topic}</p>`;
          for (const letter of ['A', 'B', 'C', 'D']) {
            const key = `option${letter}` as keyof typeof q;
            if (q[key]) {
              const isCorrect = q.correctAnswer === letter;
              const isWrong = q.userAnswer === letter && !isCorrect;
              html += `<div class="option ${isCorrect ? 'is-correct' : ''} ${isWrong ? 'is-wrong' : ''}">${letter}) ${q[key]}${isCorrect ? ' ✓' : ''}${isWrong ? ' ✗ (your answer)' : ''}</div>`;
            }
          }
          if (q.explanation) html += `<div class="explanation">${q.explanation}</div>`;
          html += `</div>`;
        }
      }

      html += `<p class="meta" style="text-align:center;margin-top:40px;">Generated by MedStudy</p></body></html>`;

      printWindow.document.write(html);
      printWindow.document.close();
      printWindow.onload = () => {
        printWindow.print();
      };
    } catch {
      printWindow.close();
      toast.error('Export failed');
    } finally {
      setLoading(false);
    }
  }

  if (!isMax) {
    return (
      <Button variant="outline" size="sm" disabled className="gap-1.5 opacity-60">
        <Lock className="w-3.5 h-3.5" /> {label} <TierBadge tier="max" size="sm" />
      </Button>
    );
  }

  return (
    <Button variant="outline" size="sm" onClick={handleExport} disabled={loading} className="gap-1.5">
      {loading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Download className="w-3.5 h-3.5" />}
      {label}
    </Button>
  );
}
